title: [The Jain-Taylor Family Cookbook]
description:
author: Patrick Jain-Taylor
avatar: "/assets/img/cookbook.png"
round-avatar: true
social-network-links:
  email: "patrick.andrew.taylor@gmail.com"
  github: patrick-andrew-jain-taylor
  twitter: PJainTaylor
  linkedin: pjaintaylor
url-pretty: "recipes.jain-taylor.family"
share-links-active:
  github: true
  twitter: true
  linkedin: true
rss-description: Cookbook for Jain-Taylor Recipes
keywords: "my,list,of,keywords"
plugins:
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
paginate: 5
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-cayman
