remote_theme: "mmistakes/so-simple-theme@3.2.0"
locale: "en-us"
title: "The Jain-Taylor Family Cookbook"
description: "Generations of Recipes, From GG to You and Me"
url: "https://recipes.jaintaylor.family"
logo: "/assets/img/cookbook.jpg"
date_format: "%B %-d, %Y"
round-avatar: true
# Build settings
permalink: /:categories/:title/
feed:
  path: atom.xml
# Pagination
paginate: 10
paginate_path: "/page:num/"
# Search
search_full_content: true
# Taxonomy
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
plugins:
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/
# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true
relative_links:
  enabled: true
  collections: true
readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
footer_links:
  - title: Twitter
    url: https://twitter.com/pjaintaylor
    icon: fab fa-twitter-square
  - title: LinkedIn
    url: https://linkedin.com/in/pjaintaylor
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/patrick-andrew-jain-taylor
    icon: fab fa-github-square
