remote_theme: mmistakes/so-simple-theme
locale: en-US
title: "The Jain-Taylor Family Cookbook"
description: "Generations of Recipes, From GG to You and Me"\
baseurl: "/recipes"
url: "https://recipes.jain-taylor.family"
logo: "/assets/img/cookbook.jpg"
date_format: "%B %-d, %Y"
round-avatar: true
plugins:
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-sitemap
paginate: 10
paginate_path: /page:num/
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
author:
  name: Patrick Jain-Taylor
  picture: "/assets/img/pjt.jpg"
  email: "patrick.andrew.taylor@gmail.com"
  twitter: PJainTaylor
  links:
    - title: Twitter
      url: https://twitter.com/pjaintaylor
      icon: fab fa-twitter-square
    - title: LinkedIn
      url: https://linkedin.com/in/pjaintaylor
      icon: fab fa-linkedin-square
    - title: GitHub
      url: https://github.com/patrick-andrew-jain-taylor
      icon: fab fa-github-square
footer_links:
  - title: Twitter
    url: https://twitter.com/pjaintaylor
    icon: fab fa-twitter-square
  - title: LinkedIn
    url: https://linkedin.com/in/pjaintaylor
    icon: fab fa-linkedin-square
  - title: GitHub
    url: https://github.com/patrick-andrew-jain-taylor
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
